services:
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: "./server-nodejs"
    volumes:
      - /app/node_modules
      - ./server:/app

  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./posts-project
    volumes:
      - /app/node_modules
      - ./posts-project:/app